#!/bin/bash

common="emacs zsh git source-highlight"
ag="silversearcher-ag"
vim="vim"

get_os_distribution() {
    if   [ -e /etc/debian_version ] ||
         [ -e /etc/debian_release ]; then
        # Check Ubuntu or Debian
        if [ -e /etc/lsb-release ]; then
            # Ubuntu
            distri_name="ubuntu"
        else
            # Debian
            distri_name="debian"
        fi
    elif [ -e /etc/arch-release ]; then
        # Arch Linux
        distri_name="arch"
    else
        # Other
        echo "unkown distribution"
        distri_name="unkown"
    fi

    echo ${distri_name}
}

case "$(get_os_distribution)" in
    "arch" )
        exit 1
        ;;
    "ubuntu" )
        sudo -S apt-get update -y
        sudo -S apt-get install -y $vim $ag $common
        ;;
    "debian" ) exit 1;;
    "unkown" ) exit 1;;
esac
