#!/bin/bash
cat << EOF > ~/.zshenv
#! /usr/bin/env zsh
# -*- mode: sh ; coding: utf-8 -*- 
#--- copy to each machine ---
export ZDOTDIR=$(MAKEFILE_DIR)zsh
source ${ZDOTDIR}/.zshenv
#---------------------------- " 
EOF
cd ~
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh