#!/bin/sh
cd $(dirname $0)
cud=$(pwd)

cat << EOF > ~/.zshenv
#! /usr/bin/env zsh 
# -*- mode: sh ; coding: utf-8 -*- 

#--- copy to each machine ---
export ZDOTDIR=$cud/.zsh
source \${ZDOTDIR}/.zshenv
#---------------------------- " 
EOF

ln -sfn $cud/dircolors ~/.dir_colors
ln -sfn $cud/most/.mostrc ~/.mostrc

go get github.com/peco/peco/cmd/peco

cd ~
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh

ln -sfn $cud/emacs ~/.emacs.d

ln -sfn $cud/texmf ~/texmf 

ln -sfn $cud/xmonad ~/.xmonad

ln -sfn $cud/sshrc/.sshrc ~/.sshrc
ln -sfn $cud/sshrc/.sshrc.d ~/.sshrc.d

cd /tmp
rm -rf ~/.icons
git clone https://github.com/gmmeyer/awesome-dangerzone
mv /tmp/awesome-dangerzone/icons ~/.icons
rm -rf /tmp/awesome-dangerzone

mkdir -p ~/.config
ln -sfn $cud/nvim ~/.config/nvim

ln -sfn $cud/peco ~/.config/peco

cd ~
git clone https://github.com/powerline/fonts
cd ~/fonts/
./install.sh

cd ~
wget https://github.com/adobe-fonts/source-han-code-jp/archive/2.011R.zip
unzip 2.011R.zip
cp ~/source-han-code-jp-2.011R/OTC/SourceHanCodeJP.ttc ~/.local/share/fonts
