#!/bin/sh

cud=$(pwd)

cat << EOF > ~/.zshenv
#! /usr/bin/env zsh 
# -*- mode: sh ; coding: utf-8 -*- 

#--- copy to each machine ---
export ZDOTDIR=$cud/zsh
source \${ZDOTDIR}/.zshenv
#---------------------------- " 
EOF

ln -sfn $cud/dircolors ~/.dir_colors

ln -sfn $cud/emacs ~/.emacs.d

ln -sfn $cud/texmf ~/texmf 

ln -sfn $cud/xmonad ~/.xmonad

cd /tmp
rm -rf ~/.icons
git clone https://github.com/gmmeyer/awesome-dangerzone
mv /tmp/awesome-dangerzone/icons ~/.icons
rm -rf /tmp/awesome-dangerzone

mkdir -p ~/.config
ln -sfn $cud/nvim ~/.config/nvim

ln -sfn $cud/peco ~/.config/peco
