#!/bin/bash
docker run -it --rm \
       -u $UID:$GID \
       -e DISPLAY=$DISPLAY \
       --device /dev/snd:/dev/snd \
       -v /dev/snd/:/dev/snd/:rw \
       -v /etc/localtime:/etc/localtime:ro \
       -v /tmp/.X11-unix/:/tmp/.X11-unix:ro \
       -v $HOME/wine:/home/wine \
       -v /run/media/tk/ボリューム/:/home/wine/vol \
       --name wine \
       wine:latest \
       /bin/bash
       $@
