# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
	call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
	call denite#custom#var('grep', 'command', ['ag'])
	call denite#custom#var('grep', 'recursive_opts', [])
	call denite#custom#var('grep', 'pattern_opt', [])
	call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
	'''
hook_add = '''
	call denite#custom#map('insert',"<C-h>",'<denite:move_to_next_line>','noremap')
	call denite#custom#map('insert',"<C-t>",'<denite:move_to_previous_line>','noremap')
	call denite#custom#map('insert',"<C-b>",'<denite:delete_char_before_caret>','noremap')
	call denite#custom#map('normal',"h",'<denite:move_to_next_line>','noremap')
	call denite#custom#map('normal',"t",'<denite:move_to_previuos_line>','noremap')
	'''
     
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
	let g:rehash256 = 1
    colorscheme molokai
	'''
