[[plugins]]
repo = 'tyru/eskk.vim'
on_map = {ic = '<Plug>'}
hook_add = '''
  imap <C-j>     <Plug>(eskk:toggle)
  cmap <C-j>     <Plug>(eskk:toggle)
'''
hook_source = '''
	let g:eskk#dictionary = {'path': '~/skk/.skk-jisyo','sorted': 1,'encoding': 'utf-8',}
	let g:eskk#large_dictionary = {'path': '~/skk/SKK-JISYO.L','sorted': 1,'encoding': 'utf-8',}
'''

[[plugins]]
repo = 'lyuts/vim-rtags'
