lsp:
  server:
    type: docker
    subtype: image
    # image subtype means creating a new container each time from a specified image
    name: template-pylsp-docker # Must be unique across all language servers
    server: template-pylsp-server # Server id of a registered server (by lsp-mode)
    launch_command: pylsp # Launch command of the language server
    # (selected by a server id specified above) in stdio mode
    # Note: launch_command is not used with container subtype servers
    # as a command is embedded in a container itself and serves as an entrypoint
  mappings:
    - source: "."
      destination: "/app"
