#!/bin/bash
docker run -it --rm \
       -u $UID:$GID \
       -e DISPLAY=$DISPLAY \
       -v /etc/localtime:/etc/localtime:ro \
       -v /tmp/.X11-unix/:/tmp/.X11-unix:ro \
       -v $HOME/wine:/home/wine \
       --device /dev/snd \
       --name wine \
       wine:latest \
       /bin/bash
       $@
